apiVersion: apps/v1
kind: Deployment
metadata:
  name: small-project-go
  labels:
    app: small-project-go
spec:
  selector:
    matchLabels:
      app: small-project-go
  template:
    metadata:
      labels:
        app: small-project-go
    spec:
      containers:
      - name: small-project-go
        image: sureshkapileswarapu/small-project-go:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
