apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: small-project-go
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sample.my-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: small-project-go
            port:
              number: 80
