apiVersion: v1
kind: Service
metadata:
  name: small-project-go
  labels:
    app: small-project-go
spec:
  selector:
    app: small-project-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer